version: '3.4'

services:
  m2:
    image: m2
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5003"
      ]
    ports:
      - 5003:5003
      - 5678:5678
    environment:
      - FLASK_APP=main.py

    depends_on:
      - sqlitedb
      - mongodb

  mongodb:
    container_name: my-mongodb-container
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: always

  sqlitedb:
    container_name: my-sqlite-container
    image: tiangolo/uwsgi-nginx-flask:python3.8
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///onlineshop_.db
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
    volumes:
      - C:/Users/Hind/Documents:/path/to/sqlite/data
    ports:
      - "5002:5002"
    restart: always

volumes:
  mongodb-data:
